modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL = "https://github.com/phoillows/Relics-Of-Time/issues" #optional
license="MIT"
[[mods]] #mandatory
modId="rot" #mandatory
version="0.2.0" #mandatory
displayName="Relics of Time" #mandatory
displayURL="ยง9Discord: https://discord.gg/Xxx3n6Xw" #optional
logoFile="logo.png" #optional
credits="Phoillows, SennaHN, Kent, Tellioari, Seentro, Alphaxenopete82, PriorMentation, DinoFazbearYT, Magne L" #optional
authors="Gibblygjabble" #optional
description='''Relics of Time allows you to revive prehistoric animals and plants using machinery.'''

[[dependencies.rot]] #optional
    modId="geckolib3" #mandatory
    mandatory=true #mandatory
    versionRange="[3.1,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.rot]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.rot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
